name: run

on:
#   schedule:
#     - cron: '0 */7 * * *'

  workflow_dispatch:


jobs:
  build-run:
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v7

    - name: build
      run: |
        pip install -r requirements.txt
        pip install -e .

    - name: run
      run: nix-auto-update