name: Runner

on:
#   schedule:
#     - cron: '0 */7 * * *'

  workflow_dispatch:


jobs:
  build-run:
    runs-on: "ubuntu-latest"

    permissions:
      contents: write
      pull-requests: write
  
    steps:
    - uses: actions/checkout@v7

    - name: Installer Nix
      uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Caching Nixpkgs
      uses: actions/cache@v4
      env:
          cache-name: cache-pkgs
      with:
        path: ~/nixpkgs
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}

    - name: Clone repo
      run: |
        git clone git@github.com:lukas-sgx/nixpkgs --depth=1
        cd nixpkgs
        git config user.name "lukas-sgx"
        git config user.email "lukas.soigneux@epitech.eu"
        git pull
    - name: Build
      run: |
        pip install -r requirements.txt
        pip install -e .

    - name: Run
      run: |
        git config --global user.name "lukas-sgx"
        git config --global user.email "lukas.soigneux@epitech.eu"
        nix-auto-update
      env:
        GH_TOKEN: ${{ secrets.GTHUB_ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GTHUB_ACCESS_TOKEN }}